### ISSUE TITLE
Arguments for harness generation

### ISSUE THREAD

**Issue by mimicria** [ex0dus-0x/fuzzable#10]
Hello!
I got the results of the analysis and now I would like to automatically generate the harness for this functions
![screen_fuzzable](https://user-images.githubusercontent.com/89445008/188541413-d1731c53-3af9-4e32-99af-5db690682295.png)

I tried to call like this:
```
# generate harness from a candidate
$ fuzzable create-harness ~/nDPI/src/lib/ndpi_main.c --symbol-name=ndpi_set_bitmask_protocol_detection
```
But I get an error
```
Unknown format
[37m[41mfuzzable error:[0m [31mWrong filetype, or does not support synthesizing harnesses for C/C++ source code yet.
```

**Comment by ex0dus-0x** [comment]
I have not yet added support to synthesizing harnesses for source code targets yet, given that the template for generation (`templates/linux_source_harness.cpp`) is quite rudimentary, and that generation would just be copy-pasting that specific harness for use.

If this is a feature that you believe should be prioritized let me know! Will create a separate issue documenting how this might be rolled out.

**Comment by mimicria** [comment]
@ex0dus-0x 
It would be nice, since I would like to use this utility in CI pipeline for automatic fuzzing some small targets
