### ISSUE TITLE
binary ninja plugin install broken

### ISSUE THREAD

**Issue by psifertex** [ex0dus-0x/fuzzable#11]
It looks like the latest release has broken the binary ninja plugin manager support. I'm removing it from the plugin manager for now, if you'd like to re-add it, please move the binja plugin to a separate folder, add an appropriate [plugin.json](https://binary.ninja/2019/07/04/plugin-manager-2.0.html) and let us know and we'll add it back.

**Comment by psifertex** [comment]
Also, note that squashing all the old history while still leaving the original release is a bit odd since it's not actually possible to get back to that state of the repo. I was super confused as to how this plugin would have ever worked even though it was around for some time until I realized what had happened.

**Comment by ex0dus-0x** [comment]
It looks like I refactored out the `plugin.json` before generating the release. This has since been fixed. At this point we're going to do approach releases a lot more carefully given the project traction.

**Comment by psifertex** [comment]
Unfortunately this is still broken. Specifically, the release is looked up by tag which is the version number which doesn't exist as you can see at:

https://api.github.com/repos/ex0dus-0x/fuzzable/contents/plugin.json?ref=2.0

This is described in a bit more detail in the "Creating a release" section: https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release where it talks about both creating the tag that we can look up the specific version of the files as well as the GH release which triggers everything to happen.

**Comment by psifertex** [comment]
Thanks, that did it!
