### ISSUE TITLE
setup.py not found in manual install

### ISSUE THREAD

**Issue by mimicria** [ex0dus-0x/fuzzable#9]
Hello!
With manual install got error:
`Directory '.' is not installable. File 'setup.py' not found.`
after
```
$ cd fuzzable/
$ pip install .
```

**Comment by ex0dus-0x** [comment]
Hey! What version of `pip` is being used to complete the installation? It may be that it is not recognizing the `pyproject.toml` manifest present in the repository.

**Comment by mimicria** [comment]
> Hey! What version of `pip` is being used to complete the installation? It may be that it is not recognizing the `pyproject.toml` manifest present in the repository.

Oh, damn, it was pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
Now i upgrade it to pip 21.3.1, it start to work, but still got errors:
```
ERROR: Could not find a version that satisfies the requirement prettytable<4.0.0,>=3.3.0 (from fuzzable) (from versions: 0.3, 0.4, 0.5, 0.6, 0.6.1, 0.7.1, 0.7.2, 1.0.0, 1.0.1, 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.5.0)
ERROR: No matching distribution found for prettytable<4.0.0,>=3.3.0
```
What python/pip versions are needed ?
